name: GitHub Metrics

on:
  schedule: # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: sabrinamaral
          template: classic
          base: "" # disables header/activity clutter
          # Enable languages plugin
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%
          plugin_languages_details: bytes-size, percentage
          plugin_languages_analysis_timeout: 15
        
