name: GitHub Metrics

on:
  schedule: # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Basic setup
          user: sabrinamaral
          template: classic
          base: header, languages
          config_timezone: America/Sao_Paulo
